#!/bin/bash
set -e
ADB=${ADB:-adb}
VLC=${VLC:-vlc}

SNDCPY_SCRIPT=$(realpath -- "$0")
echo "Set SNDCPY_SCRIPT to " $SNDCPY_SCRIPT

SNDCPY_PATH=$(dirname -- "$SNDCPY_SCRIPT")
echo "Set SNDCPY_PATH to " $SNDCPY_PATH

SNDCPY_APK=${SNDCPY_APK:-$SNDCPY_PATH/sndcpy.apk} 
echo "Set SNDCPY_APK to " $SNDCPY_APK

SNDCPY_PORT=${SNDCPY_PORT:-28200}
echo "Set SNDCPY_PORT to " $SNDCPY_PORT

serial=
if [[ $# -ge 1 ]]
then
    serial="-s $1"
    echo "Waiting for device $1..."
else
    echo 'Waiting for device...'
fi

"$ADB" $serial wait-for-device
"$ADB" $serial install -t -r -g "$SNDCPY_APK" ||
{
    echo 'Uninstalling existing version first...'
    "$ADB" $serial uninstall com.rom1v.sndcpy
    "$ADB" $serial install -t -g "$SNDCPY_APK"
}

"$ADB" $serial forward tcp:$SNDCPY_PORT localabstract:sndcpy
"$ADB" $serial shell am start com.rom1v.sndcpy/.MainActivity
echo "Press Enter once audio capture is authorized on the device to start playing..."
read dummy
"$VLC" -Idummy --demux rawaud --network-caching=0 --play-and-exit tcp://localhost:"$SNDCPY_PORT"
